### ISSUE TITLE
Advice on preventing sql injection

### ISSUE THREAD

**Issue by finlaydotb** [dyedgreen/deno-sqlite#112]
Hi there,

From reading through the documentation it seems the library is used by writing SQL queries directly as strings to be executed.

This looks susceptible to sql injection attacks.

Are there any functionality within the library that can help prevent such attacks? And what are the general security advice when using deno-sqlite?

Thanks!

**Comment by dyedgreen** [comment]
Hey, yes. This library let's you run SQL queries directly agains SQLite. So if you do some funny string interpolations, you will end up with SQLi vulnerabilities.

SQLite does help you here though: You can run queries with placeholders and bind the values you want to put in:
```javascript
// binding the values protects agains SQLi :)
db.query("INSERT INTO users (name, email) VALUES (?, ?);", ["my name", "my@email.com"]);
```
(see the example in the docs: https://dyedgreen.github.io/deno-sqlite/#/examples?id=binding-values-to-queries)

Since you are confused about this though, it might make sense to explain this more clearly in the reference doc comment as well (so it shows up on docs.deno.land).

[The api docs](https://doc.deno.land/https/deno.land/x/sqlite@v2.3.2/src/db.ts#DB) do give you a SQLi safe example, but currently they don't specifically call out SQLi. Do you have any ideas on how to word something like this, such that it would help with your query when reading the docs? 😅
