### ISSUE TITLE
interface `PreparedQuery` is not exported

### ISSUE THREAD

**Issue by MierenManz** [dyedgreen/deno-sqlite#118]
PreparedQuery is a interface for prepared queries, but as of v2.4.0 it is not exported

I think it it a good idea for it to be exported in the `mod.ts`

**Comment by dyedgreen** [comment]
The type definitions are not exported from the top level `mod.ts`, but you should be able to import them quite easily from where they are defined:

```typescript
import { DB } from "https://deno.land/x/sqlite/mod.ts";
import { PreparedQuery } from "https://deno.land/x/sqlite/src/db.ts";
```

But I agree that it could be cleaner to re-export them, since then users don’t have to depend on a specific folder structure which might change between versions.

**Comment by MierenManz** [comment]
should I make a pr so that `PreparedQuery` get's exported in mod.ts aswell?

**Comment by dyedgreen** [comment]
That would be amazing 🤩

I think we could also export the other public types in the api, when doing that:
- `PreparedQuery` (db.ts)
- `QueryParam` (db.ts)
- `ColumnName` (rows.ts)

**Comment by dyedgreen** [comment]
Sure, no worries. Good luck with your exams 🍀
