### ISSUE TITLE
Provide a way to access `columns()` when a query result is empty 

### ISSUE THREAD

**Issue by lodry** [dyedgreen/deno-sqlite#135]
result.columns() triggers error when there is no results for query

**Comment by dyedgreen** [comment]
This is the expected behavior, and results from the Rows object automatically cleaning up any statements which have completed.

I believe a good solution here might be to add the `columns` to the prepared query interface instead (since with a prepared query, the user is responsible for finalizing the statements, meaning the statement would still be available).

If something like this is added, it would also make sense to remove / deprecate the `columns` accessor on the `Rows` class.

**Comment by dyedgreen** [comment]
You can also use `.columns()` on a prepared query, which doesn't require a non empty result and is available in the latest tagged version and on master.
