### ISSUE TITLE
Allow specifying vfs from DB constructor

### ISSUE THREAD

**Issue by lrowe** [dyedgreen/deno-sqlite#185]
I'm exploring the possibility of writing my own SQLite VFS so that I can control file operations. Following the example browser bundle I can override the vfs used in my app globally by specifying an import map:
```json
{
  "imports": {
    "https://deno.land/x/sqlite@v3.3.0/build/vfs.js": "./vfs.ts",
    "sqlite/": "https://deno.land/x/sqlite@v3.3.0/"
  }
}
```
However it would be more convenient and more flexible if a custom vfs env function could be supplied to the DB constructor. The required changes look to be:

* https://github.com/dyedgreen/deno-sqlite/blob/master/src/db.ts:
  * add `env` to SqliteOptions (should probably come up with a better name)
  * pass env into instantiate.
* https://github.com/dyedgreen/deno-sqlite/blob/master/build/hack/bundle.js:
  * In instantiate use the passed in `env` to decorate the importObject.

One potential downside I see with this simple implementation approach is that it could make it more awkward to reuse WebAssembly.Instance in the future. I don't know if that could be a performance consideration if one wanted to instantiate a new database per request (or maybe it should be possible to reopen a closed DB instance?)

**Comment by dyedgreen** [comment]
Thanks for writing up the issue!

I feel like supporting different / pluggable VFS components is not really a first class concern of this library. Rather, I want to provide a package for SQLite in deno that 'just works', and plays well with file system permissions etc. A really nice side-effect of this, is that this project also produces a WASM binary which can be used to run SQLite in different contexts.

If you want to deploy the JavaScript part of this library in a novel context, you can use an import map to swap out the VFS, like we do for the web-version. You can also use this approach to build a wrapper which creates databases and dynamically swaps out different VFS implementations if you want (compare with the web version, which also has custom functions for opening a database connection).

Re multiple connections: You probably don't want to open a database connection per request, since each connection is a self-contained WASM module, which would make this approach quite expensive in practice.

**Comment by lrowe** [comment]
> Re multiple connections: You probably don't want to open a database connection per request, since each connection is a self-contained WASM module, which would make this approach quite expensive in practice.

This was why I was thinking that it should be possible to reopen a closed DB instance with another file to minimize the cost. While that might still be a nicety, turns out it is possible at the SQLite level using [ATTACH](https://www.sqlite.org/lang_attach.html) and this works with this WebAssembly build.
