### ISSUE TITLE
Add json1 support

### ISSUE THREAD

**Issue by jolonf** [dyedgreen/deno-sqlite#20]
Include the sqlite json1 extension:

https://www.sqlite.org/json1.html

**Comment by dyedgreen** [comment]
Thank you for opening an issue @jolonf!

I'm not sure the added build complexity/ performance impact of the extension is worth the benefit. Especially since JavaScript/ TypeScript has very strong JSON support already (as opposed to say C, where these utilities are much more helpful).

Could you elaborate on your use case for the extension?

**Comment by jolonf** [comment]
It looks like deno-sqlite is only memory-based at the moment? In that case there probably isn't much of an advantage to having the json1 extension.

For file-based DBs the json1 extension allows json paths to be indexed for efficient retrieval.

**Comment by hsjoberg** [comment]
@jolonf `deno-sqlite` is not only memory based, you need to manually call `save` function with the db as argument.

**Comment by dyedgreen** [comment]
@jolonf, @hsjoberg Yeah, that is correct. Although internally the database connections are file-based, these files are completely represented and held inside the WASM memory and not saved to disc automatically. (This is probably the most significant difference from standard SQLite you'd have in C).

From what I can tell, most of the functions in the json1 extension are not really necessary when the data comes from JS, as the same manipulations can be done in JS-land easily. Although the ability to index and select on the JSON contents might be helpful to some users.

But I feel that overall, the benefit probably does not justify the added maintenance burden and the performance/ size impact on consumers who don't use the extension.

I think a good way forward here might be to have more extensive documentation and guidance on how to make customised builds, so that advanced users can alter the loaded extensions to their specific needs (see also issue #25).

**Comment by jeremyBanks** [comment]
I would like to encourage you to reconsider. 🙂

I am currently using Node with the NPM `sqlite3` package for a small project, because it supports the JSON functions out-of-the-box. I would have needed to do a custom build to enable them for Python or Ruby's primary SQLite libraries, and that seemed daunting.

Thanks to your work on this repository, and Deno's and SQLite's simplicity, I was pleased to find that making a custom build with JSON1 enabled was very easy, just a matter of changing a few lines: b0214ce46a1d2a9d143b4c016c7df4dfaede10e6. 🙏 My needs are satisfied, but I think there are a lot of potential users who would appreciating having it enabled by default, as [it is in the competing NPM library](https://www.npmjs.com/package/sqlite3#features).

I am indeed using SQLite in-memory, however these functions are still extremely useful. As is common in JavaScript, I have a lot of JSON objects flying around, and I like to be able to use the JSON functions to add constraints to sort-of gradually-type them (in the TypeScript fashion) when hitting the database. The ability to enforce constraints and index on them is a major reason people might choose to use a database engine, and in this JavaScript/TypeScript context, being able to use JSON to express those would can be very valuable. 😃
