### ISSUE TITLE
Run SQLite inside WebWorker

### ISSUE THREAD

**Issue by montyanderson** [dyedgreen/deno-sqlite#205]
I can't help but notice that using this library means blocking the main thread regularly.

I've tried running a database inside a WebWorker but was instead wondering if this should be a library feature. It could be totally transparent to application code outside of calling async/vs sync methods.

**Comment by dyedgreen** [comment]
Using a worker requires either read or net permissions to allow for the dynamic import. Workers also don’t work well when bundling since they force you to have a separate file.

I think it’s relatively simple to use this library in a worker just by running a worker yourself (or by building a more opinionated library on top of this one). I don’t think it makes sense for this to live in this library though.
