### ISSUE TITLE
get sql statement prepared by prepareQuery as text

### ISSUE THREAD

**Issue by elycheikhsmail** [dyedgreen/deno-sqlite#213]
how can I get sql statement prepared by prepareQuery as text/string

**Comment by dyedgreen** [comment]
We could add bindings to support `sqlite3_sql` and `sqlite3_expanded_sql`. Although expanding the SQL might be a bit awkward since in our API we bind parameters immediately before running a query and clear parameters after every query.

But maybe something like the below might work?
```typescript
class PreparedQuery {
  function sql(params?: P): string
}
```

Which returns the result of `sqlite3_sql` if called with no parameters and `sqlite3_expanded_sql` if called with a parameter set?
