### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by Dialga** [dyedgreen/deno-sqlite#25]
Hi,
Can you add some documentation on how to build this library?
Thanks

**Comment by dyedgreen** [comment]
Thanks for submitting the issue @Dialga!

Currently there is [some guidance](https://dyedgreen.github.io/deno-sqlite/#/contributing?id=prerequisites) in the documentation.

However, usually uses won't need to build the WASM files themselves (as a pre-build version is distributed with the library.) Thus using the project should be as simple as:

```javascript
import { DB } from "https://deno.land/x/sqlite/mod.ts";

let db = new DB();
// use db ...
```

Generally, for building the WASM files, you would use the `Makefile` provided in the `build` directory. So to make a release you'd e.g. run
```bash
# assume in project root
cd build
make WASI=path/to/wasi/root release
```
to build the WASM, or
``` bash
# assume in build dir
make download && make amalgamation
```
to re-build the amalgamation files (which are also checked into source).

Let me know if that helps. And please do outline what information you'd specifically want and what for, so that the documentation can be updated to help people coming to the project in the future! (If you feel you have some time, a PR with such additions would also be amazing 😉)

**Comment by Dialga** [comment]
Yes I asked this because I want to make a custom sqlite build for myself, for example enabling sqlite ft5.
Where should WASI point to? I know nothing about building wasm files.

**Comment by dyedgreen** [comment]
I see, that makes sense.

`WASI` should point to the top-level directory where you installed the latest WASI SDK (v8), which you can download for your system from https://github.com/CraneStation/wasi-sdk/releases.

There are some more details on how it all fits together for this project in particular [here](https://dyedgreen.github.io/deno-sqlite/#/contributing?id=prerequisites), and there is also [this blog post](https://tilman.xyz/blog/2019/12/building-webassembly-for-deno/) which has some more details regarding building WASM for deno.

Let me know if these resources are sufficient to get you started, and if they could be improved in any ways 😊

**Comment by dyedgreen** [comment]
The new build/ Makefile should be easier to use now. Closing for now.
