### ISSUE TITLE
UTF data in SQLite errors

### ISSUE THREAD

**Issue by mocox** [dyedgreen/deno-sqlite#64]
I am using 'https://deno.land/x/sqlite/mod.ts' to open a db that has some data that has chinese characters i get the following error

**error: invalid utf-8 sequence of 1 bytes from index 39**

i can open this fine in python and see it in sqlite explorer but not in deno, i set read permissions on it

Thanks Mo

**Comment by dyedgreen** [comment]
Hi @mocox, thank you for reporting this! Could you provide a minimal example (ideally with a database), which reproduces the error, so that I can look into it more closely?

**Comment by mocox** [comment]
do you have an email or somewhere i can send to as i dont want to make my database public

**Comment by dyedgreen** [comment]
You can use [this](https://send.firefox.com) to send files, or create a sample database with utf-8 content that triggers the bug, whatever is easier for you 😄

**Comment by mocox** [comment]
uploaded to there. added the project with the database

**Comment by dyedgreen** [comment]
Can you forward me the link 😅

**Comment by mocox** [comment]
oh sorry, forgot that https://send.firefox.com/download/31f9f2b168509e0a/#YoL0QsnK62AUEkyyVzg29Q


> Can you forward me the link 😅

**Comment by dyedgreen** [comment]
Got the file, let me have a look 😄

**Comment by mocox** [comment]
> Got the file, let me have a look 😄

ok thanks, let me know if im being a dork!!

**Comment by mocox** [comment]
I was running in VS code with the extensions by denoland

**Comment by dyedgreen** [comment]
I can't seem to reproduce the same error, specifically the following outputs the table contents correctly:
```js
const db = new sqlite.DB('./path/to/db/file.db');
console.log([...db.query("SELECT Id, Radical FROM DictCN")]);
```

Although I also noticed that you have this line:
```js
const rows = db.query("select Id, Radical from DictCN").done();
```
which will result in `rows` being `undefined`, since the following is happening:
1. Execute a select query against the database
2. Call `done()` on the resulting rows, which discards any further results and finalizes the query, then returns nothing
3. Assign the return from `.done()` to `rows`, leaving `rows` undefined

What you want to be doing is something more like this:
```js
for (const [Id, Radical] of db.query("SELECT Id, Radical FROM DictCN")) {
    console.log(`Id = ${Id}, Radical = ${Radical}`);
}
```

None of these explain the UTF-8 error though. When I run your code, the database is opened and returns the result as expected. Do you have **the call-stack** of your error, and what kind of environment are you running deno in? E.g. I was using deno `1.0.4` on a Mac to test your code.

**Comment by mocox** [comment]
I added you code 

and still just get this, maybe i am running it wrong
am using VSCode but nothing will log to console either

this is my output: -

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\General Development\Playground\Deno\deno01> cd data
PS C:\General Development\Playground\Deno\deno01\data> deno run --allow-net  dictcn.db --allow-read data.ts
error: invalid utf-8 sequence of 1 bytes from index 39
PS C:\General Development\Playground\Deno\deno01\data>

**Comment by dyedgreen** [comment]
You should also need to give write permissions to the script so try `deno run --allow-read --allow-write data.ts`

**Comment by mocox** [comment]
Bingo! thanks that worked now, must have had the wrong command string
thanks, and sorry to trouble you

**Comment by dyedgreen** [comment]
Yeah, I just noticed what happened, your command was:
> `deno run --allow-net dictcn.db --allow-read data.ts`

which means the first file passed to `deno run` was `dictcn.db`, so deno tried to execute the database file as the script, which leads to the error message you got.

Happy to see the issue resolved 😄
